version: "3.3"

services:
  btc_sig_miner:
    container_name: btc_sig_miner
    build:
      context: bitcoind_signet_miner_plugnplay
    image: bitcoind_signet_miner
    network_mode: "host"
    expose:
      - "38333"
      - "38332"

  c-lightning:
    container_name: c-lightning
    build:
      context: c-lightning
    image: core_lightning
    network_mode: "host"
    expose:
      - "39735"
